In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

test = pd.read_csv("data/idsc_dataset.csv", delimiter=";")

In [2]:
test["data"] = pd.to_datetime(test["dt_dep"])

/tmp/ipykernel_3252060/180993028.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  test["data"] = pd.to_datetime(test["dt_dep"])

In [4]:
len(test["path"].unique())

969

In [10]:
import requests

def download_images(df):
    unlock = False
    for row in df["path"].unique():

        # Faz o download da imagem usando a biblioteca requests
        try:
            data = row.split('/')[-1]
            path = row
            
            # Extrai o nome do arquivo da URL
            nome_arquivo = path.split('/')[-1]
            print(nome_arquivo)
    
            # Define o caminho onde a imagem será salva
            pasta_destino = f'data/img/test/'
        
            response = requests.get(path)
        
            # Verifica se a resposta foi bem sucedida (código 200)
            if response.status_code == 200:
                with open(f'{pasta_destino}{data}.jpg', 'wb') as file:
                    file.write(response.content)
                    print(f"Imagem {nome_arquivo} salva em {pasta_destino}")
            else:
                print(f"Erro ao baixar a imagem {nome_arquivo}")
        except:
            pass

In [11]:
download_images(test)

S11635384_202308211100.jpg
Imagem S11635384_202308211100.jpg salva em data/img/test/
S11635384_202309150000.jpg
Imagem S11635384_202309150000.jpg salva em data/img/test/
S11635384_202309030100.jpg
Imagem S11635384_202309030100.jpg salva em data/img/test/
S11635384_202309150300.jpg
Imagem S11635384_202309150300.jpg salva em data/img/test/
S11635384_202308230000.jpg
Imagem S11635384_202308230000.jpg salva em data/img/test/
S11635384_202309130900.jpg
Imagem S11635384_202309130900.jpg salva em data/img/test/
S11635384_202308210900.jpg
Imagem S11635384_202308210900.jpg salva em data/img/test/
S11635384_202309111300.jpg
Imagem S11635384_202309111300.jpg salva em data/img/test/
S11635384_202309132000.jpg
Imagem S11635384_202309132000.jpg salva em data/img/test/
S11635384_202309012200.jpg
Imagem S11635384_202309012200.jpg salva em data/img/test/
S11635384_202309161300.jpg
Imagem S11635384_202309161300.jpg salva em data/img/test/
S11635384_202308302300.jpg
Imagem S11635384_202308302300.jpg salva em data/img/test/
S11635384_202308290600.jpg
Imagem S11635384_202308290600.jpg salva em data/img/test/
S11635384_202308292200.jpg
Imagem S11635384_202308292200.jpg salva em data/img/test/
S11635384_202308222300.jpg
Imagem S11635384_202308222300.jpg salva em data/img/test/
S11635384_202309111100.jpg
Imagem S11635384_202309111100.jpg salva em data/img/test/
S11635384_202308151900.jpg
Imagem S11635384_202308151900.jpg salva em data/img/test/
S11635384_202308151100.jpg
Imagem S11635384_202308151100.jpg salva em data/img/test/
S11635384_202308201700.jpg
Imagem S11635384_202308201700.jpg salva em data/img/test/
S11635384_202308312000.jpg
Imagem S11635384_202308312000.jpg salva em data/img/test/
S11635384_202309131100.jpg
Imagem S11635384_202309131100.jpg salva em data/img/test/
S11635384_202308281400.jpg
Imagem S11635384_202308281400.jpg salva em data/img/test/
S11635384_202309172300.jpg
Imagem S11635384_202309172300.jpg salva em data/img/test/
S11635384_202308221100.jpg
Imagem S11635384_202308221100.jpg salva em data/img/test/
S11635384_202308291200.jpg
Imagem S11635384_202308291200.jpg salva em data/img/test/
S11635384_202309031800.jpg
Imagem S11635384_202309031800.jpg salva em data/img/test/
S11635384_202308270200.jpg
Imagem S11635384_202308270200.jpg salva em data/img/test/
S11635384_202309061100.jpg
Imagem S11635384_202309061100.jpg salva em data/img/test/
S11635384_202308231100.jpg
Imagem S11635384_202308231100.jpg salva em data/img/test/
S11635384_202309121400.jpg
Imagem S11635384_202309121400.jpg salva em data/img/test/
S11635384_202308272100.jpg
Imagem S11635384_202308272100.jpg salva em data/img/test/
S11635384_202308161600.jpg
Imagem S11635384_202308161600.jpg salva em data/img/test/
S11635384_202309120200.jpg
Imagem S11635384_202309120200.jpg salva em data/img/test/
S11635384_202308160000.jpg
Imagem S11635384_202308160000.jpg salva em data/img/test/
S11635384_202309192100.jpg
Imagem S11635384_202309192100.jpg salva em data/img/test/
S11635384_202309171300.jpg
Imagem S11635384_202309171300.jpg salva em data/img/test/
S11635384_202309082000.jpg
Imagem S11635384_202309082000.jpg salva em data/img/test/
S11635384_202308261900.jpg
Imagem S11635384_202308261900.jpg salva em data/img/test/
S11635384_202309210100.jpg
Imagem S11635384_202309210100.jpg salva em data/img/test/
S11635384_202308302000.jpg
Imagem S11635384_202308302000.jpg salva em data/img/test/
S11635384_202309051300.jpg
Imagem S11635384_202309051300.jpg salva em data/img/test/
S11635384_202308290100.jpg
Imagem S11635384_202308290100.jpg salva em data/img/test/
S11635384_202309071200.jpg
Imagem S11635384_202309071200.jpg salva em data/img/test/
S11635384_202308211800.jpg
Imagem S11635384_202308211800.jpg salva em data/img/test/
S11635384_202308241600.jpg
Imagem S11635384_202308241600.jpg salva em data/img/test/
S11635384_202308201200.jpg
Imagem S11635384_202308201200.jpg salva em data/img/test/
S11635384_202308150700.jpg
Imagem S11635384_202308150700.jpg salva em data/img/test/
S11635384_202309031300.jpg
Imagem S11635384_202309031300.jpg salva em data/img/test/
S11635384_202308200600.jpg
Imagem S11635384_202308200600.jpg salva em data/img/test/
S11635384_202308160300.jpg
Imagem S11635384_202308160300.jpg salva em data/img/test/
S11635384_202309072200.jpg
Imagem S11635384_202309072200.jpg salva em data/img/test/
S11635384_202309211400.jpg
Imagem S11635384_202309211400.jpg salva em data/img/test/
S11635384_202309192300.jpg
Imagem S11635384_202309192300.jpg salva em data/img/test/
S11635384_202309120000.jpg
Imagem S11635384_202309120000.jpg salva em data/img/test/
S11635384_202309170100.jpg
Imagem S11635384_202309170100.jpg salva em data/img/test/
S11635384_202309101700.jpg
Imagem S11635384_202309101700.jpg salva em data/img/test/
S11635384_202309110000.jpg
Imagem S11635384_202309110000.jpg salva em data/img/test/
S11635384_202309081100.jpg
Imagem S11635384_202309081100.jpg salva em data/img/test/
S11635384_202308172000.jpg
Imagem S11635384_202308172000.jpg salva em data/img/test/
S11635384_202308241900.jpg
Imagem S11635384_202308241900.jpg salva em data/img/test/
S11635384_202308231800.jpg
Imagem S11635384_202308231800.jpg salva em data/img/test/
S11635384_202308301600.jpg
Imagem S11635384_202308301600.jpg salva em data/img/test/
S11635384_202308241300.jpg
Imagem S11635384_202308241300.jpg salva em data/img/test/
S11635384_202308310200.jpg
Imagem S11635384_202308310200.jpg salva em data/img/test/
S11635384_202309062000.jpg
Imagem S11635384_202309062000.jpg salva em data/img/test/
S11635384_202309061500.jpg
Imagem S11635384_202309061500.jpg salva em data/img/test/
S11635384_202308221500.jpg
Imagem S11635384_202308221500.jpg salva em data/img/test/
S11635384_202308260800.jpg
Imagem S11635384_202308260800.jpg salva em data/img/test/
S11635384_202309061800.jpg
Imagem S11635384_202309061800.jpg salva em data/img/test/
S11635384_202309220100.jpg
Imagem S11635384_202309220100.jpg salva em data/img/test/
S11635384_202309250000.jpg
Imagem S11635384_202309250000.jpg salva em data/img/test/
S11635384_202309181800.jpg
Imagem S11635384_202309181800.jpg salva em data/img/test/
S11635384_202308182200.jpg
Imagem S11635384_202308182200.jpg salva em data/img/test/
S11635384_202309240200.jpg
Imagem S11635384_202309240200.jpg salva em data/img/test/
S11635384_202308180300.jpg
Imagem S11635384_202308180300.jpg salva em data/img/test/
S11635384_202309232200.jpg
Imagem S11635384_202309232200.jpg salva em data/img/test/
S11635384_202309131400.jpg
Imagem S11635384_202309131400.jpg salva em data/img/test/
S11635384_202309011000.jpg
Imagem S11635384_202309011000.jpg salva em data/img/test/
S11635384_202309122000.jpg
Imagem S11635384_202309122000.jpg salva em data/img/test/
S11635384_202309111900.jpg
Imagem S11635384_202309111900.jpg salva em data/img/test/
S11635384_202309240000.jpg
Imagem S11635384_202309240000.jpg salva em data/img/test/
S11635384_202308290900.jpg
Imagem S11635384_202308290900.jpg salva em data/img/test/
S11635384_202309140700.jpg
Imagem S11635384_202309140700.jpg salva em data/img/test/
S11635384_202308180000.jpg
Imagem S11635384_202308180000.jpg salva em data/img/test/
S11635384_202309101300.jpg
Imagem S11635384_202309101300.jpg salva em data/img/test/
S11635384_202308281500.jpg
Imagem S11635384_202308281500.jpg salva em data/img/test/
S11635384_202308272300.jpg
Imagem S11635384_202308272300.jpg salva em data/img/test/
S11635384_202308270500.jpg
Imagem S11635384_202308270500.jpg salva em data/img/test/
S11635384_202308181300.jpg
Imagem S11635384_202308181300.jpg salva em data/img/test/
S11635384_202309121500.jpg
Imagem S11635384_202309121500.jpg salva em data/img/test/
S11635384_202308310900.jpg
Imagem S11635384_202308310900.jpg salva em data/img/test/
S11635384_202309031200.jpg
Imagem S11635384_202309031200.jpg salva em data/img/test/
S11635384_202308312100.jpg
Imagem S11635384_202308312100.jpg salva em data/img/test/
S11635384_202308180900.jpg
Imagem S11635384_202308180900.jpg salva em data/img/test/
S11635384_202309151600.jpg
Imagem S11635384_202309151600.jpg salva em data/img/test/
S11635384_202308231200.jpg
Imagem S11635384_202308231200.jpg salva em data/img/test/
S11635384_202308230900.jpg
Imagem S11635384_202308230900.jpg salva em data/img/test/
S11635384_202309171900.jpg
Imagem S11635384_202309171900.jpg salva em data/img/test/
S11635384_202309182200.jpg
Imagem S11635384_202309182200.jpg salva em data/img/test/
S11635384_202308271600.jpg
Imagem S11635384_202308271600.jpg salva em data/img/test/
S11635384_202308291400.jpg
Imagem S11635384_202308291400.jpg salva em data/img/test/
S11635384_202308162100.jpg
Imagem S11635384_202308162100.jpg salva em data/img/test/
S11635384_202308200800.jpg
Imagem S11635384_202308200800.jpg salva em data/img/test/
S11635384_202308301700.jpg
Imagem S11635384_202308301700.jpg salva em data/img/test/
S11635384_202309091200.jpg
Imagem S11635384_202309091200.jpg salva em data/img/test/
S11635384_202309021400.jpg
Imagem S11635384_202309021400.jpg salva em data/img/test/
S11635384_202309191200.jpg
Imagem S11635384_202309191200.jpg salva em data/img/test/
S11635384_202308250900.jpg
Imagem S11635384_202308250900.jpg salva em data/img/test/
S11635384_202308211200.jpg
Imagem S11635384_202308211200.jpg salva em data/img/test/
S11635384_202309211300.jpg
Imagem S11635384_202309211300.jpg salva em data/img/test/
S11635384_202309032300.jpg
Imagem S11635384_202309032300.jpg salva em data/img/test/
S11635384_202309151500.jpg
Imagem S11635384_202309151500.jpg salva em data/img/test/
S11635384_202308151500.jpg
Imagem S11635384_202308151500.jpg salva em data/img/test/
S11635384_202309042300.jpg
Imagem S11635384_202309042300.jpg salva em data/img/test/
S11635384_202308201400.jpg
Imagem S11635384_202308201400.jpg salva em data/img/test/
S11635384_202309141200.jpg
Imagem S11635384_202309141200.jpg salva em data/img/test/
S11635384_202309011700.jpg
Imagem S11635384_202309011700.jpg salva em data/img/test/
S11635384_202308300900.jpg
Imagem S11635384_202308300900.jpg salva em data/img/test/
S11635384_202309071400.jpg
Imagem S11635384_202309071400.jpg salva em data/img/test/
S11635384_202309041200.jpg
Imagem S11635384_202309041200.jpg salva em data/img/test/
S11635384_202309231400.jpg
Imagem S11635384_202309231400.jpg salva em data/img/test/
S11635384_202309200000.jpg
Imagem S11635384_202309200000.jpg salva em data/img/test/
S11635384_202308251300.jpg
Imagem S11635384_202308251300.jpg salva em data/img/test/
S11635384_202309192000.jpg
Imagem S11635384_202309192000.jpg salva em data/img/test/
S11635384_202308231600.jpg
Imagem S11635384_202308231600.jpg salva em data/img/test/
S11635384_202308281000.jpg
Imagem S11635384_202308281000.jpg salva em data/img/test/
S11635384_202308161700.jpg
Imagem S11635384_202308161700.jpg salva em data/img/test/
S11635384_202308161100.jpg
Imagem S11635384_202308161100.jpg salva em data/img/test/
S11635384_202309242100.jpg
Imagem S11635384_202309242100.jpg salva em data/img/test/
S11635384_202309101100.jpg
Imagem S11635384_202309101100.jpg salva em data/img/test/
S11635384_202309081700.jpg
Imagem S11635384_202309081700.jpg salva em data/img/test/
S11635384_202308271300.jpg
Imagem S11635384_202308271300.jpg salva em data/img/test/
S11635384_202309201200.jpg
Imagem S11635384_202309201200.jpg salva em data/img/test/
S11635384_202309041100.jpg
Imagem S11635384_202309041100.jpg salva em data/img/test/
S11635384_202309102300.jpg
Imagem S11635384_202309102300.jpg salva em data/img/test/
S11635384_202309091500.jpg
Imagem S11635384_202309091500.jpg salva em data/img/test/
S11635384_202308231700.jpg
Imagem S11635384_202308231700.jpg salva em data/img/test/
S11635384_202309162200.jpg
Imagem S11635384_202309162200.jpg salva em data/img/test/
S11635384_202309181500.jpg
Imagem S11635384_202309181500.jpg salva em data/img/test/
S11635384_202308271500.jpg
Imagem S11635384_202308271500.jpg salva em data/img/test/
S11635384_202308202000.jpg
Imagem S11635384_202308202000.jpg salva em data/img/test/
S11635384_202309221700.jpg
Imagem S11635384_202309221700.jpg salva em data/img/test/
S11635384_202309021200.jpg
Imagem S11635384_202309021200.jpg salva em data/img/test/
S11635384_202308271200.jpg
Imagem S11635384_202308271200.jpg salva em data/img/test/
S11635384_202308251700.jpg
Imagem S11635384_202308251700.jpg salva em data/img/test/
S11635384_202309020800.jpg
Imagem S11635384_202309020800.jpg salva em data/img/test/
S11635384_202309140600.jpg
Imagem S11635384_202309140600.jpg salva em data/img/test/
S11635384_202308261100.jpg
Imagem S11635384_202308261100.jpg salva em data/img/test/
S11635384_202309121700.jpg
Imagem S11635384_202309121700.jpg salva em data/img/test/
S11635384_202309101200.jpg
Imagem S11635384_202309101200.jpg salva em data/img/test/
S11635384_202309201300.jpg
Imagem S11635384_202309201300.jpg salva em data/img/test/
S11635384_202308252200.jpg
Imagem S11635384_202308252200.jpg salva em data/img/test/
S11635384_202309211600.jpg
Imagem S11635384_202309211600.jpg salva em data/img/test/
S11635384_202309041500.jpg
Imagem S11635384_202309041500.jpg salva em data/img/test/
S11635384_202308300000.jpg
Imagem S11635384_202308300000.jpg salva em data/img/test/
S11635384_202308180800.jpg
Imagem S11635384_202308180800.jpg salva em data/img/test/
S11635384_202308252000.jpg
Imagem S11635384_202308252000.jpg salva em data/img/test/
S11635384_202308181100.jpg
Imagem S11635384_202308181100.jpg salva em data/img/test/
S11635384_202309141900.jpg
Imagem S11635384_202309141900.jpg salva em data/img/test/
S11635384_202309020100.jpg
Imagem S11635384_202309020100.jpg salva em data/img/test/
S11635384_202308151400.jpg
Imagem S11635384_202308151400.jpg salva em data/img/test/
S11635384_202308191400.jpg
Imagem S11635384_202308191400.jpg salva em data/img/test/
S11635384_202309051600.jpg
Imagem S11635384_202309051600.jpg salva em data/img/test/
S11635384_202308190800.jpg
Imagem S11635384_202308190800.jpg salva em data/img/test/
S11635384_202308161900.jpg
Imagem S11635384_202308161900.jpg salva em data/img/test/
S11635384_202309021000.jpg
Imagem S11635384_202309021000.jpg salva em data/img/test/
S11635384_202308161000.jpg
Imagem S11635384_202308161000.jpg salva em data/img/test/
S11635384_202309102000.jpg
Imagem S11635384_202309102000.jpg salva em data/img/test/
S11635384_202309081600.jpg
Imagem S11635384_202309081600.jpg salva em data/img/test/
S11635384_202309160600.jpg
Imagem S11635384_202309160600.jpg salva em data/img/test/
S11635384_202308171400.jpg
Imagem S11635384_202308171400.jpg salva em data/img/test/
S11635384_202309131000.jpg
Imagem S11635384_202309131000.jpg salva em data/img/test/
S11635384_202309032100.jpg
Imagem S11635384_202309032100.jpg salva em data/img/test/
S11635384_202308220800.jpg
Imagem S11635384_202308220800.jpg salva em data/img/test/
S11635384_202308220000.jpg
Imagem S11635384_202308220000.jpg salva em data/img/test/
S11635384_202309120900.jpg
Imagem S11635384_202309120900.jpg salva em data/img/test/
S11635384_202308291900.jpg
Imagem S11635384_202308291900.jpg salva em data/img/test/
S11635384_202309161700.jpg
Imagem S11635384_202309161700.jpg salva em data/img/test/
S11635384_202308201100.jpg
Imagem S11635384_202308201100.jpg salva em data/img/test/
S11635384_202309191500.jpg
Imagem S11635384_202309191500.jpg salva em data/img/test/
S11635384_202309140900.jpg
Imagem S11635384_202309140900.jpg salva em data/img/test/
S11635384_202309151100.jpg
Imagem S11635384_202309151100.jpg salva em data/img/test/
S11635384_202308300500.jpg
Imagem S11635384_202308300500.jpg salva em data/img/test/
S11635384_202309021500.jpg
Imagem S11635384_202309021500.jpg salva em data/img/test/
S11635384_202309052300.jpg
Imagem S11635384_202309052300.jpg salva em data/img/test/
S11635384_202309012300.jpg
Imagem S11635384_202309012300.jpg salva em data/img/test/
S11635384_202308151000.jpg
Imagem S11635384_202308151000.jpg salva em data/img/test/
S11635384_202309192200.jpg
Imagem S11635384_202309192200.jpg salva em data/img/test/
S11635384_202309230000.jpg
Imagem S11635384_202309230000.jpg salva em data/img/test/
S11635384_202308212100.jpg
Imagem S11635384_202308212100.jpg salva em data/img/test/
S11635384_202308171200.jpg
Imagem S11635384_202308171200.jpg salva em data/img/test/
S11635384_202309081200.jpg
Imagem S11635384_202309081200.jpg salva em data/img/test/
S11635384_202309182100.jpg
Imagem S11635384_202309182100.jpg salva em data/img/test/
S11635384_202309230900.jpg
Imagem S11635384_202309230900.jpg salva em data/img/test/
S11635384_202308230800.jpg
Imagem S11635384_202308230800.jpg salva em data/img/test/
S11635384_202309132100.jpg
Imagem S11635384_202309132100.jpg salva em data/img/test/
S11635384_202308170900.jpg
Imagem S11635384_202308170900.jpg salva em data/img/test/
S11635384_202308221000.jpg
Imagem S11635384_202308221000.jpg salva em data/img/test/
S11635384_202309160300.jpg
Imagem S11635384_202309160300.jpg salva em data/img/test/
S11635384_202309051900.jpg
Imagem S11635384_202309051900.jpg salva em data/img/test/
S11635384_202308281800.jpg
Imagem S11635384_202308281800.jpg salva em data/img/test/
S11635384_202308251500.jpg
Imagem S11635384_202308251500.jpg salva em data/img/test/
S11635384_202308210700.jpg
Imagem S11635384_202308210700.jpg salva em data/img/test/
S11635384_202308232000.jpg
Imagem S11635384_202308232000.jpg salva em data/img/test/
S11635384_202308261600.jpg
Imagem S11635384_202308261600.jpg salva em data/img/test/
S11635384_202309051500.jpg
Imagem S11635384_202309051500.jpg salva em data/img/test/
S11635384_202309111400.jpg
Imagem S11635384_202309111400.jpg salva em data/img/test/
S11635384_202309101500.jpg
Imagem S11635384_202309101500.jpg salva em data/img/test/
S11635384_202309112100.jpg
Imagem S11635384_202309112100.jpg salva em data/img/test/
S11635384_202309172100.jpg
Imagem S11635384_202309172100.jpg salva em data/img/test/
S11635384_202308151200.jpg
Imagem S11635384_202308151200.jpg salva em data/img/test/
S11635384_202308232300.jpg
Imagem S11635384_202308232300.jpg salva em data/img/test/
S11635384_202309142000.jpg
Imagem S11635384_202309142000.jpg salva em data/img/test/
S11635384_202309050900.jpg
Imagem S11635384_202309050900.jpg salva em data/img/test/
S11635384_202309191100.jpg
Imagem S11635384_202309191100.jpg salva em data/img/test/
S11635384_202308301500.jpg
Imagem S11635384_202308301500.jpg salva em data/img/test/
S11635384_202309221000.jpg
Imagem S11635384_202309221000.jpg salva em data/img/test/
S11635384_202309172000.jpg
Imagem S11635384_202309172000.jpg salva em data/img/test/
S11635384_202308192100.jpg
Imagem S11635384_202308192100.jpg salva em data/img/test/
S11635384_202309140400.jpg
Imagem S11635384_202309140400.jpg salva em data/img/test/
S11635384_202309081300.jpg
Imagem S11635384_202309081300.jpg salva em data/img/test/
S11635384_202308181600.jpg
Imagem S11635384_202308181600.jpg salva em data/img/test/
S11635384_202308150200.jpg
Imagem S11635384_202308150200.jpg salva em data/img/test/
S11635384_202308171600.jpg
Imagem S11635384_202308171600.jpg salva em data/img/test/
S11635384_202308170100.jpg
Imagem S11635384_202308170100.jpg salva em data/img/test/
S11635384_202308282300.jpg
Imagem S11635384_202308282300.jpg salva em data/img/test/
S11635384_202308241100.jpg
Imagem S11635384_202308241100.jpg salva em data/img/test/
S11635384_202309230800.jpg
Imagem S11635384_202309230800.jpg salva em data/img/test/
S11635384_202308181200.jpg
Imagem S11635384_202308181200.jpg salva em data/img/test/
S11635384_202308251100.jpg
Imagem S11635384_202308251100.jpg salva em data/img/test/
S11635384_202309172200.jpg
Imagem S11635384_202309172200.jpg salva em data/img/test/
S11635384_202308281700.jpg
Imagem S11635384_202308281700.jpg salva em data/img/test/
S11635384_202308200200.jpg
Imagem S11635384_202308200200.jpg salva em data/img/test/
S11635384_202308262300.jpg
Imagem S11635384_202308262300.jpg salva em data/img/test/
S11635384_202308310100.jpg
Imagem S11635384_202308310100.jpg salva em data/img/test/

In [16]:
import os
import subprocess
import pandas as pd
import json
from multiprocessing import Pool, cpu_count

# Function to be mapped
def process_file(file):
    log = []
    data_list = []
    file_path = os.path.join('data/img/test/', file)
    print(file)
    try:
        output = subprocess.check_output(['python3', 'utils/decodeImage.py', file_path])
        output = json.loads(output)
        
        polyCount = 0
        for poly in output:
            verticeCount = 0
            for vertice in poly:
                x = vertice[0][0]
                y = vertice[0][1]
                data_list.append({'data': file, 'X': x, 'Y': y, 'poly': polyCount, 'vertice': verticeCount})
                verticeCount = verticeCount + 1
            polyCount = polyCount + 1
        log.append(f'{file}: sem erros\n')
    except subprocess.CalledProcessError as err:
        log.append(f'{file}: erro na execução - {err}\n')
    
    return data_list, log


# Use Pool to create subprocesses
with Pool(min(8, cpu_count())) as p:
    results = p.map(process_file, os.listdir('data/img/test/'))

# Combine results
all_data = []
all_logs = []
for data, log in results:
    all_data.extend(data)
    all_logs.extend(log)

# Creates dataframe from the data
dataset = pd.DataFrame(all_data)

# Cria o arquivo de log
with open('log/log2.txt', 'w') as log_file:
    log_file.writelines(all_logs)

# Export dataframe to csv
dataset.to_csv('data/testImageData.csv', index=False)

S11635384_202309110900.jpg.jpgS11635384_202308242300.jpg.jpgS11635384_202308151600.jpg.jpgS11635384_202309140500.jpg.jpgS11635384_202308261900.jpg.jpg




S11635384_202309022300.jpg.jpgS11635384_202309110500.jpg.jpg
S11635384_202309181200.jpg.jpg

S11635384_202309182300.jpg.jpg
S11635384_202308291600.jpg.jpg
S11635384_202308310500.jpg.jpg
S11635384_202309101100.jpg.jpg
S11635384_202309031000.jpg.jpg
S11635384_202308191800.jpg.jpg
S11635384_202308170700.jpg.jpg
S11635384_202308201700.jpg.jpg
S11635384_202309051200.jpg.jpg
S11635384_202308240100.jpg.jpg
S11635384_202309091700.jpg.jpg
S11635384_202308150300.jpg.jpg
S11635384_202309210800.jpg.jpg
S11635384_202309202300.jpg.jpg
S11635384_202309171600.jpg.jpg
S11635384_202309061000.jpg.jpg
S11635384_202309231400.jpg.jpg
S11635384_202308181100.jpg.jpg
S11635384_202308211500.jpg.jpg
S11635384_202309012000.jpg.jpg
S11635384_202308250100.jpg.jpg
S11635384_202309142200.jpg.jpg
S11635384_202308260900.jpg.jpg
S11635384_202309010500.jpg.jpg
S11635384_202309182100.jpg.jpg
S11635384_202308212100.jpg.jpg
S11635384_202309240300.jpg.jpg
S11635384_202309171100.jpg.jpg
S11635384_202309031400.jpg.jpg
S11635384_202309182200.jpg.jpg
S11635384_202309240700.jpg.jpg
S11635384_202308171100.jpg.jpg
S11635384_202309131000.jpg.jpg
S11635384_202309152300.jpg.jpg
S11635384_202309080200.jpg.jpg
S11635384_202308192200.jpg.jpg
S11635384_202309041600.jpg.jpg
S11635384_202309180200.jpg.jpg
S11635384_202309231700.jpg.jpg
S11635384_202309230900.jpg.jpg
S11635384_202309211700.jpg.jpg
S11635384_202309172300.jpg.jpg
S11635384_202308160900.jpg.jpg
S11635384_202309240800.jpg.jpg
S11635384_202308181700.jpg.jpg
S11635384_202308190200.jpg.jpg
S11635384_202308171300.jpg.jpg
S11635384_202309091800.jpg.jpg
S11635384_202309210900.jpg.jpg
S11635384_202308312100.jpg.jpg
S11635384_202309070300.jpg.jpg
S11635384_202308300200.jpg.jpg
S11635384_202309011400.jpg.jpg
S11635384_202308252000.jpg.jpg
S11635384_202309021700.jpg.jpg
S11635384_202309090800.jpg.jpg
S11635384_202308290500.jpg.jpg
S11635384_202308271800.jpg.jpg
S11635384_202308281800.jpg.jpg
S11635384_202309060200.jpg.jpg
S11635384_202309161800.jpg.jpg
S11635384_202308160800.jpg.jpg
S11635384_202309030800.jpg.jpg
S11635384_202308281300.jpg.jpg
S11635384_202309141900.jpg.jpg
S11635384_202308280200.jpg.jpg
S11635384_202309191500.jpg.jpg
S11635384_202309081500.jpg.jpg
S11635384_202309032200.jpg.jpg
S11635384_202309151900.jpg.jpg
S11635384_202309151400.jpg.jpg
S11635384_202309180000.jpg.jpg
S11635384_202309161000.jpg.jpg
S11635384_202309151000.jpg.jpg
S11635384_202309052100.jpg.jpg
S11635384_202309090900.jpg.jpg
S11635384_202309082200.jpg.jpg
S11635384_202309162100.jpg.jpg
S11635384_202309220700.jpg.jpg
S11635384_202309021800.jpg.jpg
S11635384_202309211500.jpg.jpg
S11635384_202308151800.jpg.jpg
S11635384_202308281000.jpg.jpg
S11635384_202308262200.jpg.jpg
S11635384_202309231600.jpg.jpg
S11635384_202309240500.jpg.jpg
S11635384_202309030900.jpg.jpg
S11635384_202309061300.jpg.jpg
S11635384_202308171000.jpg.jpg
S11635384_202309081100.jpg.jpg
S11635384_202308211900.jpg.jpg
S11635384_202309031600.jpg.jpg
S11635384_202308312200.jpg.jpg
S11635384_202309191200.jpg.jpg
S11635384_202308211700.jpg.jpg
S11635384_202309031300.jpg.jpg
S11635384_202309100800.jpg.jpg
S11635384_202309151600.jpg.jpg
S11635384_202309111100.jpg.jpg
S11635384_202309052300.jpg.jpg
S11635384_202309201500.jpg.jpg
S11635384_202308251900.jpg.jpg
S11635384_202309051800.jpg.jpg
S11635384_202308180500.jpg.jpg
S11635384_202309180300.jpg.jpg
S11635384_202309072000.jpg.jpg
S11635384_202308161700.jpg.jpg
S11635384_202309052000.jpg.jpg
S11635384_202309150600.jpg.jpg
S11635384_202308182100.jpg.jpg
S11635384_202308161400.jpg.jpg
S11635384_202308301900.jpg.jpg
S11635384_202309071200.jpg.jpg
S11635384_202309171200.jpg.jpg
S11635384_202308271700.jpg.jpg
S11635384_202308180800.jpg.jpg
S11635384_202308161900.jpg.jpg
S11635384_202309171900.jpg.jpg
S11635384_202309200500.jpg.jpg
S11635384_202309230700.jpg.jpg
S11635384_202309031200.jpg.jpg
S11635384_202308180200.jpg.jpg
S11635384_202309022000.jpg.jpg
S11635384_202308221200.jpg.jpg
S11635384_202308300500.jpg.jpg
S11635384_202309090200.jpg.jpg
S11635384_202308300600.jpg.jpg
S11635384_202309020900.jpg.jpg
S11635384_202308311300.jpg.jpg
S11635384_202308200000.jpg.jpg
S11635384_202309010400.jpg.jpg
S11635384_202309111000.jpg.jpg
S11635384_202309121000.jpg.jpg
S11635384_202308251400.jpg.jpg
S11635384_202308251600.jpg.jpg
S11635384_202309222300.jpg.jpg
S11635384_202308282200.jpg.jpg
S11635384_202308172000.jpg.jpg
S11635384_202308191000.jpg.jpg
S11635384_202308231000.jpg.jpg
S11635384_202308151700.jpg.jpg
S11635384_202309131800.jpg.jpg
S11635384_202309021500.jpg.jpg
S11635384_202308160000.jpg.jpg
S11635384_202308300000.jpg.jpg
S11635384_202308261800.jpg.jpg
S11635384_202309020100.jpg.jpg
S11635384_202308261200.jpg.jpg
S11635384_202309032300.jpg.jpg
S11635384_202308190300.jpg.jpg
S11635384_202309112100.jpg.jpg
S11635384_202308212300.jpg.jpg
S11635384_202309021200.jpg.jpg
S11635384_202309140300.jpg.jpg
S11635384_202309030300.jpg.jpg
S11635384_202308181500.jpg.jpg
S11635384_202308211200.jpg.jpg
S11635384_202309242300.jpg.jpg
S11635384_202309090400.jpg.jpg
S11635384_202309111300.jpg.jpg
S11635384_202308230500.jpg.jpg
S11635384_202309142000.jpg.jpg
S11635384_202309091300.jpg.jpg
S11635384_202309222200.jpg.jpg
S11635384_202308192100.jpg.jpg
S11635384_202308311700.jpg.jpg
S11635384_202308152200.jpg.jpg
S11635384_202309031100.jpg.jpg
S11635384_202309220100.jpg.jpg
S11635384_202308310300.jpg.jpg
S11635384_202309210600.jpg.jpg
S11635384_202309120000.jpg.jpg
S11635384_202309231300.jpg.jpg
S11635384_202308310700.jpg.jpg
S11635384_202309111700.jpg.jpg
S11635384_202309162000.jpg.jpg
S11635384_202309042100.jpg.jpg
S11635384_202309070600.jpg.jpg
S11635384_202309030100.jpg.jpg
S11635384_202308200100.jpg.jpg
S11635384_202308181000.jpg.jpg
S11635384_202308261000.jpg.jpg
S11635384_202309210500.jpg.jpg
S11635384_202309201000.jpg.jpg
S11635384_202309030600.jpg.jpg
S11635384_202308252100.jpg.jpg
S11635384_202309022100.jpg.jpg
S11635384_202309102000.jpg.jpg
S11635384_202309061200.jpg.jpg
S11635384_202309241200.jpg.jpg
S11635384_202308281400.jpg.jpg
S11635384_202309181600.jpg.jpg
S11635384_202309232200.jpg.jpg
S11635384_202308240400.jpg.jpg
S11635384_202309042300.jpg.jpg
S11635384_202309050600.jpg.jpg
S11635384_202309081600.jpg.jpg
S11635384_202309131600.jpg.jpg
S11635384_202309161700.jpg.jpg
S11635384_202309190300.jpg.jpg
S11635384_202308152300.jpg.jpg
S11635384_202308282300.jpg.jpg
S11635384_202308160600.jpg.jpg
S11635384_202309241800.jpg.jpg
S11635384_202308231900.jpg.jpg
S11635384_202309051900.jpg.jpg
S11635384_202308232200.jpg.jpg
S11635384_202309081000.jpg.jpg
S11635384_202308160700.jpg.jpg
S11635384_202309051100.jpg.jpg
S11635384_202308282000.jpg.jpg
S11635384_202309130800.jpg.jpg
S11635384_202308191600.jpg.jpg
S11635384_202309161400.jpg.jpg
S11635384_202309230300.jpg.jpg
S11635384_202308251200.jpg.jpg
S11635384_202309130900.jpg.jpg
S11635384_202309100500.jpg.jpg
S11635384_202309011900.jpg.jpg
S11635384_202309050900.jpg.jpg
S11635384_202308191400.jpg.jpg
S11635384_202309201700.jpg.jpg
S11635384_202309021600.jpg.jpg
S11635384_202308300900.jpg.jpg
S11635384_202309110300.jpg.jpg
S11635384_202308181400.jpg.jpg
S11635384_202308182200.jpg.jpg
S11635384_202309250000.jpg.jpg
S11635384_202308162000.jpg.jpg
S11635384_202309111900.jpg.jpg
S11635384_202308220900.jpg.jpg
S11635384_202309150100.jpg.jpg
S11635384_202308280600.jpg.jpg
S11635384_202308241000.jpg.jpg
S11635384_202308310600.jpg.jpg
S11635384_202309221200.jpg.jpg
S11635384_202308200700.jpg.jpg
S11635384_202308242000.jpg.jpg
S11635384_202308190700.jpg.jpg
S11635384_202309011100.jpg.jpg
S11635384_202308280800.jpg.jpg
S11635384_202308230700.jpg.jpg
S11635384_202309070000.jpg.jpg
S11635384_202309211900.jpg.jpg
S11635384_202309202000.jpg.jpg
S11635384_202308241700.jpg.jpg
S11635384_202309171700.jpg.jpg
S11635384_202308300100.jpg.jpg
S11635384_202309162200.jpg.jpg
S11635384_202309060100.jpg.jpg
S11635384_202308280100.jpg.jpg
S11635384_202309211100.jpg.jpg
S11635384_202308290900.jpg.jpg
S11635384_202309131200.jpg.jpg
S11635384_202309061500.jpg.jpg
S11635384_202308190800.jpg.jpg
S11635384_202309091600.jpg.jpg
S11635384_202308181900.jpg.jpg
S11635384_202308180100.jpg.jpg
S11635384_202308290000.jpg.jpg
S11635384_202308250800.jpg.jpg
S11635384_202308231400.jpg.jpg
S11635384_202309171800.jpg.jpg
S11635384_202308182300.jpg.jpg
S11635384_202308301600.jpg.jpg
S11635384_202309160300.jpg.jpg
S11635384_202308290200.jpg.jpg
S11635384_202308270000.jpg.jpg
S11635384_202309071300.jpg.jpg
S11635384_202308171700.jpg.jpg
S11635384_202309170300.jpg.jpg
S11635384_202309080800.jpg.jpg
S11635384_202309041100.jpg.jpg
S11635384_202308151200.jpg.jpg
S11635384_202308151300.jpg.jpg
S11635384_202309060800.jpg.jpg
S11635384_202308241600.jpg.jpg
S11635384_202308311600.jpg.jpg
S11635384_202308161200.jpg.jpg
S11635384_202309221400.jpg.jpg
S11635384_202308210000.jpg.jpg
S11635384_202309091900.jpg.jpg
S11635384_202309150000.jpg.jpg
S11635384_202308230400.jpg.jpg
S11635384_202308310900.jpg.jpg
S11635384_202308270600.jpg.jpg
S11635384_202308260700.jpg.jpg
S11635384_202309120800.jpg.jpg
S11635384_202308161600.jpg.jpg
S11635384_202309011600.jpg.jpg
S11635384_202309200200.jpg.jpg
S11635384_202308301400.jpg.jpg
S11635384_202309051000.jpg.jpg
S11635384_202309080700.jpg.jpg
S11635384_202308242100.jpg.jpg
S11635384_202308251800.jpg.jpg
S11635384_202309231100.jpg.jpg
S11635384_202309140200.jpg.jpg
S11635384_202309050000.jpg.jpg
S11635384_202308302300.jpg.jpg
S11635384_202308270900.jpg.jpg
S11635384_202308221800.jpg.jpg
S11635384_202308182000.jpg.jpg
S11635384_202309041400.jpg.jpg
S11635384_202309102200.jpg.jpg
S11635384_202309132100.jpg.jpg
S11635384_202309101900.jpg.jpg
S11635384_202308222200.jpg.jpg
S11635384_202309152000.jpg.jpg
S11635384_202308150400.jpg.jpg
S11635384_202308201900.jpg.jpg
S11635384_202309201200.jpg.jpg
S11635384_202309031800.jpg.jpg
S11635384_202308151500.jpg.jpg
S11635384_202309190400.jpg.jpg
S11635384_202308230300.jpg.jpg
S11635384_202309212100.jpg.jpg
S11635384_202309150700.jpg.jpg
S11635384_202309031500.jpg.jpg
S11635384_202308240000.jpg.jpg
S11635384_202308221000.jpg.jpg
S11635384_202309080500.jpg.jpg
S11635384_202309170700.jpg.jpg
S11635384_202309180700.jpg.jpg
S11635384_202309100900.jpg.jpg
S11635384_202309092200.jpg.jpg
S11635384_202308240300.jpg.jpg
S11635384_202309131900.jpg.jpg
S11635384_202308220700.jpg.jpg
S11635384_202309121900.jpg.jpg
S11635384_202309091000.jpg.jpg
S11635384_202309011200.jpg.jpg
S11635384_202308251000.jpg.jpg
S11635384_202309220200.jpg.jpg
S11635384_202309051600.jpg.jpg
S11635384_202308312300.jpg.jpg
S11635384_202309222000.jpg.jpg
S11635384_202309221600.jpg.jpg
S11635384_202308300300.jpg.jpg
S11635384_202309141600.jpg.jpg
S11635384_202309020000.jpg.jpg
S11635384_202308280700.jpg.jpg
S11635384_202308221400.jpg.jpg
S11635384_202309201600.jpg.jpg
S11635384_202308272200.jpg.jpg
S11635384_202308260800.jpg.jpg
S11635384_202309242100.jpg.jpg
S11635384_202309040400.jpg.jpg
S11635384_202308161300.jpg.jpg
S11635384_202309110200.jpg.jpg
S11635384_202309241400.jpg.jpg
S11635384_202309111400.jpg.jpg
S11635384_202309132000.jpg.jpg
S11635384_202308300400.jpg.jpg
S11635384_202309032100.jpg.jpg
S11635384_202308300700.jpg.jpg
S11635384_202309172200.jpg.jpg
S11635384_202308291300.jpg.jpg
S11635384_202308270500.jpg.jpg
S11635384_202308231800.jpg.jpg
S11635384_202309151200.jpg.jpg
S11635384_202309240100.jpg.jpg
S11635384_202309171300.jpg.jpg
S11635384_202308161000.jpg.jpg
S11635384_202308220500.jpg.jpg
S11635384_202308301300.jpg.jpg
S11635384_202309200900.jpg.jpg
S11635384_202308261300.jpg.jpg
S11635384_202308201500.jpg.jpg
S11635384_202309140800.jpg.jpg
S11635384_202309112200.jpg.jpg
S11635384_202308232300.jpg.jpg
S11635384_202309181800.jpg.jpg
S11635384_202309081900.jpg.jpg
S11635384_202308240800.jpg.jpg
S11635384_202308241300.jpg.jpg
S11635384_202309230800.jpg.jpg
S11635384_202309132200.jpg.jpg
S11635384_202309011700.jpg.jpg
S11635384_202308250000.jpg.jpg
S11635384_202308180000.jpg.jpg
S11635384_202308161800.jpg.jpg
S11635384_202308172200.jpg.jpg
S11635384_202308262000.jpg.jpg
S11635384_202309070500.jpg.jpg
S11635384_202309170800.jpg.jpg
S11635384_202309041000.jpg.jpg
S11635384_202309230100.jpg.jpg
S11635384_202308272000.jpg.jpg
S11635384_202309211800.jpg.jpg
S11635384_202308171900.jpg.jpg
S11635384_202309221800.jpg.jpg
S11635384_202309112000.jpg.jpg
S11635384_202308231300.jpg.jpg
S11635384_202308301200.jpg.jpg
S11635384_202309240600.jpg.jpg
S11635384_202308211000.jpg.jpg
S11635384_202308210700.jpg.jpg
S11635384_202309192100.jpg.jpg
S11635384_202309060900.jpg.jpg
S11635384_202309230600.jpg.jpg
S11635384_202308220300.jpg.jpg
S11635384_202309091500.jpg.jpg
S11635384_202308202200.jpg.jpg
S11635384_202309092100.jpg.jpg
S11635384_202309181300.jpg.jpg
S11635384_202309232000.jpg.jpg
S11635384_202309010700.jpg.jpg
S11635384_202308211100.jpg.jpg
S11635384_202309200800.jpg.jpg
S11635384_202308230600.jpg.jpg
S11635384_202308240500.jpg.jpg
S11635384_202308280400.jpg.jpg
S11635384_202309182000.jpg.jpg
S11635384_202309131400.jpg.jpg
S11635384_202308162100.jpg.jpg
S11635384_202309040800.jpg.jpg
S11635384_202309100000.jpg.jpg
S11635384_202309071000.jpg.jpg
S11635384_202308201600.jpg.jpg
S11635384_202309061900.jpg.jpg
S11635384_202308240200.jpg.jpg
S11635384_202309102100.jpg.jpg
S11635384_202308260100.jpg.jpg
S11635384_202308180300.jpg.jpg
S11635384_202309160200.jpg.jpg
S11635384_202308241200.jpg.jpg
S11635384_202308270300.jpg.jpg
S11635384_202308262300.jpg.jpg
S11635384_202309210000.jpg.jpg
S11635384_202309221300.jpg.jpg
S11635384_202309220500.jpg.jpg
S11635384_202309200600.jpg.jpg
S11635384_202308222100.jpg.jpg
S11635384_202309050100.jpg.jpg
S11635384_202309232100.jpg.jpg
S11635384_202309210300.jpg.jpg
S11635384_202309041700.jpg.jpg
S11635384_202308180700.jpg.jpg
S11635384_202308151100.jpg.jpg
S11635384_202309140100.jpg.jpg
S11635384_202309180400.jpg.jpg
S11635384_202308201400.jpg.jpg
S11635384_202308200600.jpg.jpg
S11635384_202309120300.jpg.jpg
S11635384_202309021400.jpg.jpg
S11635384_202309140700.jpg.jpg
S11635384_202309071500.jpg.jpg
S11635384_202308181600.jpg.jpg
S11635384_202308310200.jpg.jpg
S11635384_202309130700.jpg.jpg
S11635384_202308210200.jpg.jpg
S11635384_202309070400.jpg.jpg
S11635384_202309211200.jpg.jpg
S11635384_202309131500.jpg.jpg
S11635384_202309232300.jpg.jpg
S11635384_202308272300.jpg.jpg
S11635384_202308280500.jpg.jpg
S11635384_202308222000.jpg.jpg
S11635384_202308222300.jpg.jpg
S11635384_202308221300.jpg.jpg
S11635384_202308220200.jpg.jpg
S11635384_202309030500.jpg.jpg
S11635384_202309180800.jpg.jpg
S11635384_202308212000.jpg.jpg
S11635384_202309190800.jpg.jpg
S11635384_202309121700.jpg.jpg
S11635384_202308171400.jpg.jpg
S11635384_202308241900.jpg.jpg
S11635384_202308272100.jpg.jpg
S11635384_202309162300.jpg.jpg
S11635384_202309050300.jpg.jpg
S11635384_202309130500.jpg.jpg
S11635384_202308190000.jpg.jpg
S11635384_202309190600.jpg.jpg
S11635384_202309221500.jpg.jpg
S11635384_202308251300.jpg.jpg
S11635384_202308152100.jpg.jpg
S11635384_202309152100.jpg.jpg
S11635384_202309111200.jpg.jpg
S11635384_202309201800.jpg.jpg
S11635384_202309081300.jpg.jpg
S11635384_202309221700.jpg.jpg
S11635384_202309161200.jpg.jpg
S11635384_202308302000.jpg.jpg
S11635384_202308250300.jpg.jpg
S11635384_202308310400.jpg.jpg
S11635384_202309230400.jpg.jpg
S11635384_202308252200.jpg.jpg
S11635384_202309150200.jpg.jpg
S11635384_202308150900.jpg.jpg
S11635384_202308281200.jpg.jpg
S11635384_202308240900.jpg.jpg
S11635384_202309070900.jpg.jpg
S11635384_202308221900.jpg.jpg
S11635384_202309041900.jpg.jpg
S11635384_202309121800.jpg.jpg
S11635384_202309141800.jpg.jpg
S11635384_202309091100.jpg.jpg
S11635384_202309090700.jpg.jpg
S11635384_202309041300.jpg.jpg
S11635384_202309142300.jpg.jpg
S11635384_202309011500.jpg.jpg
S11635384_202309120200.jpg.jpg
S11635384_202309191600.jpg.jpg
S11635384_202309122200.jpg.jpg
S11635384_202309080300.jpg.jpg
S11635384_202308311200.jpg.jpg
S11635384_202309180600.jpg.jpg
S11635384_202309080000.jpg.jpg
S11635384_202308221600.jpg.jpg
S11635384_202309141400.jpg.jpg
S11635384_202309190100.jpg.jpg
S11635384_202309190700.jpg.jpg
S11635384_202309190000.jpg.jpg
S11635384_202309071400.jpg.jpg
S11635384_202308231600.jpg.jpg
S11635384_202308200900.jpg.jpg
S11635384_202308201200.jpg.jpg
S11635384_202309022200.jpg.jpg
S11635384_202309170600.jpg.jpg
S11635384_202309040600.jpg.jpg
S11635384_202308151000.jpg.jpg
S11635384_202309200100.jpg.jpg
S11635384_202308201100.jpg.jpg
S11635384_202308220100.jpg.jpg
S11635384_202309161100.jpg.jpg
S11635384_202309172100.jpg.jpg
S11635384_202309130600.jpg.jpg
S11635384_202308250500.jpg.jpg
S11635384_202309130200.jpg.jpg
S11635384_202309231800.jpg.jpg
S11635384_202308280300.jpg.jpg
S11635384_202308190600.jpg.jpg
S11635384_202309110000.jpg.jpg
S11635384_202308212200.jpg.jpg
S11635384_202309071800.jpg.jpg
S11635384_202309071700.jpg.jpg
S11635384_202309031900.jpg.jpg
S11635384_202308221100.jpg.jpg
S11635384_202309060500.jpg.jpg
S11635384_202309082000.jpg.jpg
S11635384_202309141100.jpg.jpg
S11635384_202309131100.jpg.jpg
S11635384_202309111600.jpg.jpg
S11635384_202309040300.jpg.jpg
S11635384_202309041200.jpg.jpg
S11635384_202309100600.jpg.jpg
S11635384_202309120400.jpg.jpg
S11635384_202309170900.jpg.jpg
S11635384_202309122100.jpg.jpg
S11635384_202308281500.jpg.jpg
S11635384_202309020300.jpg.jpg
S11635384_202309091200.jpg.jpg
S11635384_202309181000.jpg.jpg
S11635384_202308291700.jpg.jpg
S11635384_202308172100.jpg.jpg
S11635384_202309060700.jpg.jpg
S11635384_202309160800.jpg.jpg
S11635384_202309161600.jpg.jpg
S11635384_202309090600.jpg.jpg
S11635384_202309221100.jpg.jpg
S11635384_202309101300.jpg.jpg
S11635384_202308262100.jpg.jpg
S11635384_202309201100.jpg.jpg
S11635384_202308162300.jpg.jpg
S11635384_202309011300.jpg.jpg
S11635384_202309191800.jpg.jpg
S11635384_202308210100.jpg.jpg
S11635384_202308150100.jpg.jpg
S11635384_202309050800.jpg.jpg
S11635384_202309190900.jpg.jpg
S11635384_202309140900.jpg.jpg
S11635384_202309212000.jpg.jpg
S11635384_202308271400.jpg.jpg
S11635384_202309061800.jpg.jpg
S11635384_202308211600.jpg.jpg
S11635384_202308270200.jpg.jpg
S11635384_202308210800.jpg.jpg
S11635384_202309130300.jpg.jpg
S11635384_202308201000.jpg.jpg
S11635384_202309211600.jpg.jpg
S11635384_202309062200.jpg.jpg
S11635384_202308281100.jpg.jpg
S11635384_202308170300.jpg.jpg
S11635384_202309030700.jpg.jpg
S11635384_202309131700.jpg.jpg
S11635384_202309191900.jpg.jpg
S11635384_202309180900.jpg.jpg
S11635384_202309101600.jpg.jpg
S11635384_202309010100.jpg.jpg
S11635384_202308271600.jpg.jpg
S11635384_202309151100.jpg.jpg
S11635384_202308181300.jpg.jpg
S11635384_202309212300.jpg.jpg
S11635384_202308151900.jpg.jpg
S11635384_202309100100.jpg.jpg
S11635384_202308230000.jpg.jpg
S11635384_202309210100.jpg.jpg
S11635384_202309240000.jpg.jpg
S11635384_202309101000.jpg.jpg
S11635384_202309160100.jpg.jpg
S11635384_202309061600.jpg.jpg
S11635384_202308191900.jpg.jpg
S11635384_202309192200.jpg.jpg
S11635384_202309020700.jpg.jpg
S11635384_202309010000.jpg.jpg
S11635384_202308160200.jpg.jpg
S11635384_202308161100.jpg.jpg
S11635384_202308242200.jpg.jpg
S11635384_202308180900.jpg.jpg
S11635384_202308211400.jpg.jpg
S11635384_202308150500.jpg.jpg
S11635384_202309221900.jpg.jpg
S11635384_202309051300.jpg.jpg
S11635384_202309021900.jpg.jpg
S11635384_202309242200.jpg.jpg
S11635384_202308271200.jpg.jpg
S11635384_202308292300.jpg.jpg
S11635384_202309061100.jpg.jpg
S11635384_202308202100.jpg.jpg
S11635384_202309191400.jpg.jpg
S11635384_202309160500.jpg.jpg
S11635384_202308281900.jpg.jpg
S11635384_202308162200.jpg.jpg
S11635384_202308190900.jpg.jpg
S11635384_202309010800.jpg.jpg
S11635384_202308280900.jpg.jpg
S11635384_202309241000.jpg.jpg
S11635384_202308160400.jpg.jpg
S11635384_202308170500.jpg.jpg
S11635384_202309020600.jpg.jpg
S11635384_202308250600.jpg.jpg
S11635384_202308291400.jpg.jpg
S11635384_202309051400.jpg.jpg
S11635384_202309220300.jpg.jpg
S11635384_202309150800.jpg.jpg

In [3]:
import pandas as pd
dataset = pd.read_csv('data/testImageData.csv')

In [8]:
import pandas as pd
from shapely.geometry import Polygon

#dataset['X'] = dataset["X"].apply(lambda x: x+940)
#dataset['Y'] = dataset["Y"].apply(lambda x: x+740)
polygons = dataset.groupby(['data', 'poly'])[['X', 'Y']].apply(lambda x: Polygon(x.values))

# Calculate the centroids
df_centroids = polygons.apply(lambda polygon: polygon.centroid)
#
## Estimate the area
df_area = polygons.apply(lambda polygon: polygon.area)
#
## Create a DataFrame with the results
results = pd.DataFrame({
    'polygon': polygons.index,
    'centroid_x': [p.x for p in df_centroids],  
    'centroid_y': [p.y for p in df_centroids], 
    'area_estimate': df_area.values
})

In [9]:
results

,polygon,centroid_x,centroid_y,area_estimate
0,"(S11635384_202308150100.jpg.jpg, 0)",351.842365,1304.818924,148947.0
1,"(S11635384_202308150100.jpg.jpg, 1)",96.973030,1105.140735,52837.0
2,"(S11635384_202308150100.jpg.jpg, 2)",996.431988,1103.493383,31167.5
3,"(S11635384_202308150100.jpg.jpg, 3)",767.379381,213.143635,10684.5
4,"(S11635384_202308150100.jpg.jpg, 4)",692.609052,135.450677,11820.0
...,...,...,...,...
409030,"(S11635384_202309250000.jpg.jpg, 464)",1.500000,234.000000,12.0
409031,"(S11635384_202309250000.jpg.jpg, 465)",821.500000,1.000000,10.0
409032,"(S11635384_202309250000.jpg.jpg, 466)",949.000000,1450.000000,8.0
409033,"(S11635384_202309250000.jpg.jpg, 467)",385.000000,1450.000000,8.0
409034,"(S11635384_202309250000.jpg.jpg, 468)",1.000000,14.000000,8.0

In [10]:
results["poly"] = results["polygon"].apply(lambda x: str(x).split(",")[1].split(")")[0].replace(" ","").replace("(","").replace("'",""))
results["data"] = pd.to_datetime(results["polygon"].apply(lambda x: str(x).split(",")[0].split("_")[1].split(".")[0]))

In [11]:
results["centroid_x"] = results["centroid_x"].apply(lambda x: x + 740)
results["centroid_y"] = results["centroid_y"].apply(lambda x: x + 940)

In [12]:


import numpy as np
from scipy import interpolate

def create_transform(pixel_coords, latlon_coords):

    pixel_x, pixel_y = zip(*pixel_coords)
    lat, lon = zip(*latlon_coords)

    lat_interp = interpolate.interp1d(pixel_y, lat, fill_value="extrapolate")
    lon_interp = interpolate.interp1d(pixel_x, lon, fill_value="extrapolate")

    return lat_interp, lon_interp

def convert_pixel_to_latlong(x, y):
    lat_lon_points = [(7.455477, -77.829943), (-51.848798, -76.538633), (1.355664, -28.966528), (8.000000, -29.500000)]
    x_y_points = [(940, 740), (940, 2192), (2092, 2192), (2092, 740)]
    lat_interp, lon_interp = create_transform(x_y_points, lat_lon_points)
    return lat_interp(y), lon_interp(x)


# Para converter um ponto de pixel para lat/lon:
lat, lon = convert_pixel_to_latlong(1500, 1500) # -3.152260, -40.788782
print(lat, lon)

results["lat"] = results.apply(lambda x: convert_pixel_to_latlong(x["centroid_x"], x["centroid_y"])[1], axis=1)
results["lon"] = results.apply(lambda x: convert_pixel_to_latlong(x["centroid_x"], x["centroid_y"])[0], axis=1)
#dataset["lat"] = dataset.apply(lambda x: convert_pixel_to_latlong(x["X"], x["Y"])[1], axis=1)
#dataset["lon"] = dataset.apply(lambda x: convert_pixel_to_latlong(x["X"], x["Y"])[0], axis=1)

-23.325817134986227 -53.413304180555556

/home/bruno/.local/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py:701: RuntimeWarning: divide by zero encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
/home/bruno/.local/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py:704: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo
/home/bruno/.local/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py:701: RuntimeWarning: divide by zero encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
/home/bruno/.local/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py:704: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

In [13]:
results

,polygon,centroid_x,centroid_y,area_estimate,poly,data,lat,lon
0,"(S11635384_202308150100.jpg.jpg, 0)",1091.842365,2244.818924,148947.0,0,2023-08-15 01:00:00,-70.2682676285446,inf
1,"(S11635384_202308150100.jpg.jpg, 1)",836.973030,2045.140735,52837.0,1,2023-08-15 01:00:00,-inf,-45.79552630397732
2,"(S11635384_202308150100.jpg.jpg, 2)",1736.431988,2043.493383,31167.5,2,2023-08-15 01:00:00,-43.64979082996639,-45.72762544446794
3,"(S11635384_202308150100.jpg.jpg, 3)",1507.379381,1153.143635,10684.5,3,2023-08-15 01:00:00,-53.10857093032507,-9.029028889634912
4,"(S11635384_202308150100.jpg.jpg, 4)",1432.609052,1075.450677,11820.0,4,2023-08-15 01:00:00,-56.19622886174746,-5.826666526102398
...,...,...,...,...,...,...,...,...
409030,"(S11635384_202309250000.jpg.jpg, 464)",741.500000,1174.000000,12.0,464,2023-09-25 00:00:00,-inf,-9.888690311294766
409031,"(S11635384_202309250000.jpg.jpg, 465)",1561.500000,941.000000,10.0,465,2023-09-25 00:00:00,-50.87364753342014,-0.2848542685950406
409032,"(S11635384_202309250000.jpg.jpg, 466)",1689.000000,2390.000000,8.0,466,2023-09-25 00:00:00,-45.60850570399306,inf
409033,"(S11635384_202309250000.jpg.jpg, 467)",1125.000000,2390.000000,8.0,467,2023-09-25 00:00:00,-68.89901544357639,inf
409034,"(S11635384_202309250000.jpg.jpg, 468)",741.000000,954.000000,8.0,468,2023-09-25 00:00:00,-inf,-0.8206906143250681

In [27]:
results.to_csv("data/test_storm_areas", index=False)

In [1]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.config("spark.executor.memory", "24g").getOrCreate()
spark.conf.set('spark.sql.crossJoin.enabled', 'true')

23/10/06 12:34:15 WARN Utils: Your hostname, bruno-Inspiron-7572 resolves to a loopback address: 127.0.1.1; using 192.168.1.12 instead (on interface wlp3s0)
23/10/06 12:34:15 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/10/06 12:34:16 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [2]:

# Assuming 'df_areas' is your first dataframe with centroid and 'df_flight' is your second dataframe
df_areas = spark.read.csv('./data/test_storm_areas', inferSchema=True, header=True)
# Register your dataframes as temp views to use them in SQL
df_areas.createOrReplaceTempView('df_areas')

In [3]:
df_flight = spark.read.csv('data/test_cat62.csv', inferSchema=True, header=True)

df_flight.createOrReplaceTempView('df_flight')

In [ ]:
import numpy as np
import pandas as pd
from geopy.distance import geodesic
from shapely.geometry import Polygon
df_flight = pd.read_csv('data/test_cat62.csv')
df_areas = pd.read_csv('./data/test_storm_areas')
# Register your dataframes as temp views to use them in SQL
# Assuming df_flight and df_areas are your dataframes
df_flight['rounded_event_time'] = df_flight['data'].apply(lambda x: str(x)[:13])
df_areas['data'] = df_areas['data'].apply(lambda x: str(x)[:13])

# Join the dataframes on rounded_event_time
merged_df = pd.merge(df_flight, df_areas, left_on='rounded_event_time', right_on='data', how='left')

# Create a flag for if flight through area
def is_through_area(row):
    dist = geodesic((row['lat_x'], row['lon_x']), (row['lat_y'], row['lon_y'])).meters
    if dist <= (row['area_estimate'] / 2):
        return 1
    else:
        return 0

merged_df['flight_through_area'] = merged_df.apply(is_through_area, axis=1)

#Group by flightid and dt_radar
grouped_df = merged_df.groupby(['flightid', 'dt_radar'])

#Get the first of polygon and max of flight_through_area
result_df = grouped_df.agg({'polygon' : 'first', 'flight_through_area' : 'max'}).reset_index()

In [4]:
from pyspark.sql.functions import *
df_flight = df_flight.withColumn("dt_radar", to_timestamp(df_flight["dt_radar"] / 1000))

In [5]:

df_flight.createOrReplaceTempView('df_flight')

In [6]:
df_areas.show()

+--------------------+------------------+------------------+-------------+----+-------------------+-------------------+-------------------+
|             polygon|        centroid_x|        centroid_y|area_estimate|poly|               data|                lat|                lon|
+--------------------+------------------+------------------+-------------+----+-------------------+-------------------+-------------------+
|('S11635384_20230...| 1291.842364509971|2044.8189244048779|     148947.0|   0|2023-08-15 01:00:00| -62.00922162160016| -45.78226186865345|
|('S11635384_20230...|1036.9730302628839|1845.1407347124175|      52837.0|   1|2023-08-15 01:00:00| -72.53410940813013| -37.55189021582304|
|('S11635384_20230...|1936.4319884495067|1843.4933825298788|      31167.5|   2|2023-08-15 01:00:00| -35.39074482302195|-37.483989356313664|
|('S11635384_20230...|1707.3793813468108| 953.1436348604676|      10684.5|   3|2023-08-15 01:00:00| -44.84952492338063|-0.7853928014806364|
|('S11635384_20230...|1632.6090524534688| 875.4506768189509|      11820.0|   4|2023-08-15 01:00:00| -47.93718285480301|  2.416969562051876|
|('S11635384_20230...|1707.1798199462178| 2173.035367707237|       2851.0|   5|2023-08-15 01:00:00| -44.85776585732416| -51.06711036416402|
|('S11635384_20230...|1316.8714988662773| 1903.311674993179|      17714.5|   6|2023-08-15 01:00:00|-60.975637760786526|-39.949590528724805|
|('S11635384_20230...|1394.7721887550201|1724.8281459170014|       4980.0|   7|2023-08-15 01:00:00| -57.75871085196734| -32.59282422155726|
|('S11635384_20230...| 1775.319880418535|2121.8960696386175|       1895.5|   8|2023-08-15 01:00:00| -42.04390638553994| -48.95924154875727|
|('S11635384_20230...|1199.4727486320216|1887.9989798126564|      16173.5|   9|2023-08-15 01:00:00| -65.82364615749901|-39.318429095739496|
|('S11635384_20230...|1611.5313969406584|1394.1658036228002|       8400.5|  10|2023-08-15 01:00:00| -48.80758948779715|-18.963524131906777|
|('S11635384_20230...| 2051.541722207411|1815.2544210432775|       3751.0|  11|2023-08-15 01:00:00|-30.637261888253647| -36.32003074629894|
|('S11635384_20230...| 1335.290424263077|1855.5794854319304|       5869.0|  12|2023-08-15 01:00:00|-60.215023999533294| -37.98215652655616|
|('S11635384_20230...|2025.3165212994563|2180.4348375679433|       1318.5|  13|2023-08-15 01:00:00|-31.720237592454453| -51.37210304804866|
|('S11635384_20230...|2043.6818346329746|1903.8175895765473|       5065.5|  14|2023-08-15 01:00:00|-30.961837753687057|  -39.9704434073097|
|('S11635384_20230...|1722.3924889199907|1368.2842313972474|       7145.0|  15|2023-08-15 01:00:00| -44.22955519261013|-17.896732817823082|
|('S11635384_20230...|1860.6820802959417|1947.5168461901135|       4595.5|  16|2023-08-15 01:00:00|-38.518854705332494| -41.77164725153524|
|('S11635384_20230...| 980.6705293509602|1716.4226647081227|       3063.5|  17|2023-08-15 01:00:00| -74.85913413481818|-32.246365580398184|
|('S11635384_20230...|1569.0888203978707| 967.1647520313813|       8922.5|  18|2023-08-15 01:00:00|-50.560265449397875|-1.3633177390125564|
|('S11635384_20230...|1942.0305357638567|1911.0481169612287|       5403.5|  19|2023-08-15 01:00:00| -35.15955152381558| -40.26847258973344|
+--------------------+------------------+------------------+-------------+----+-------------------+-------------------+-------------------+
only showing top 20 rows

In [7]:
df_flight.show()

+--------------------+------+-------+-------------------+--------------------+-------------------+--------+-------------------+-------------------+-----------+-----+-------------------+-------------------+
|            flightid|origem|destino|           hora_ref|                path|             dt_dep|   linha|                lat|                lon|flightlevel|speed|           dt_radar|               data|
+--------------------+------+-------+-------------------+--------------------+-------------------+--------+-------------------+-------------------+-----------+-----+-------------------+-------------------+
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP|-21.566934105406432| -46.78696675523622|      390.0|493.0|2022-09-06 09:05:03|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -20.21407485131328|  -46.9858187423919|      390.0|487.0|2022-09-06 08:55:00|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -23.49193196822281| -47.05615427355871|       83.0|237.0|2022-09-06 09:28:00|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP|-23.361904347508453|   -47.081812486729|       97.0|240.0|2022-09-06 09:26:00|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP|-18.248203359685327| -47.29524043997871|      390.0|482.0|2022-09-06 08:40:04|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -22.75125344666429| -46.99714005037858|      206.0|320.0|2022-09-06 09:17:02|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP|-23.474439578196623| -46.89060024432908|       59.0|162.0|2022-09-06 09:32:01|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -22.81800796296365| -47.06495176548321|      191.0|321.0|2022-09-06 09:18:03|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -22.56489162431568| -46.80920296078636|      238.0|333.0|2022-09-06 09:14:05|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP|-23.027004889808936| -47.15424493456401|      157.0|275.0|2022-09-06 09:21:03|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -23.09919237526822| -47.13855220497232|      145.0|265.0|2022-09-06 09:22:03|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -17.07550292069294| -47.53603419251553|      315.0|470.0|2022-09-06 08:31:06|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP|   -18.765505163324| -47.21358701565367|      390.0|482.0|2022-09-06 08:44:01|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP|-18.511371205795253| -47.25368800514892|      390.0|482.0|2022-09-06 08:42:05|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP|-19.154495286089787|-47.149631031490536|      390.0|482.0|2022-09-06 08:47:01|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -23.49002820708651| -46.93456720925121|       63.0|182.0|2022-09-06 09:31:01|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -23.54792127791228|-47.022624084379146|       73.0|231.0|2022-09-06 09:29:04|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -23.42650752187865|-47.068530872401205|       91.0|238.0|2022-09-06 09:27:00|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP|-15.877319427457824|  -47.8988487326812|       39.0|168.0|2022-09-06 08:19:04|2023-08-21 11:00:00|
|4f0356600f61e3fcb...|  SBBR|   SBSP|2023-10-06 11:00:00|http://satelite.c...|2023-10-06 11:53:30|SBBRSBSP| -19.42896958912036| -47.10473514155432|      390.0|480.0|2022-09-06 08:49:05|2023-08-21 11:00:00|
+--------------------+------+-------+-------------------+--------------------+-------------------+--------+-------------------+-------------------+-----------+-----+-------------------+-------------------+
only showing top 20 rows

In [8]:
# Now run the SQL Query to join these two dataframes based on your conditions
query = """
    SELECT 
        f.flightid, first(SUBSTRING(CAST(a.polygon AS STRING), 3, 13)), 
    sum(CASE
            WHEN (2 * 6371 * ASIN(SQRT(POW(SIN((f.lat - a.lat) * .0174532925 / 2), 2) 
                                   + COS(f.lat * .0174532925) * COS(a.lat * .0174532925) *
                                   POW(SIN((f.lon - a.lon) * .0174532925 / 2), 2))))
                <= (a.area_estimate / 2) THEN 1
            ELSE 0
        END) as flight_through_area
    FROM (
        SELECT *,data,
        SUBSTRING(CAST(data AS STRING), 1, 13) AS rounded_event_time
        FROM df_flight
    ) f
    LEFT JOIN df_areas a
    ON f.data = a.data
    GROUP BY f.flightid
"""
result_df = spark.sql(query)

result_df.show()

23/10/06 12:31:57 ERROR TaskMemoryManager: error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@6ecfbc2d
java.io.IOException: No space left on device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at org.apache.spark.storage.TimeTrackingOutputStream.write(TimeTrackingOutputStream.java:59)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at net.jpountz.lz4.LZ4BlockOutputStream.flushBufferedData(LZ4BlockOutputStream.java:225)
	at net.jpountz.lz4.LZ4BlockOutputStream.write(LZ4BlockOutputStream.java:178)
	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:323)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeSorterSpillWriter.write(UnsafeSorterSpillWriter.java:136)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.spillIterator(UnsafeExternalSorter.java:576)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.spill(UnsafeExternalSorter.java:231)
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:227)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:190)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:317)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:117)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:433)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.allocateMemoryForRecordIfNecessary(UnsafeExternalSorter.java:452)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.insertRecord(UnsafeExternalSorter.java:487)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.insertRow(UnsafeExternalRowSorter.java:138)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.sort_addToSorter_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1(SortAggregateExec.scala:62)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1$adapted(SortAggregateExec.scala:59)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:877)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:877)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
23/10/06 12:31:57 ERROR TaskMemoryManager: error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@140454d8
java.io.IOException: No space left on device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at org.apache.spark.storage.TimeTrackingOutputStream.write(TimeTrackingOutputStream.java:59)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at net.jpountz.lz4.LZ4BlockOutputStream.flushBufferedData(LZ4BlockOutputStream.java:225)
	at net.jpountz.lz4.LZ4BlockOutputStream.write(LZ4BlockOutputStream.java:178)
	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:323)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeSorterSpillWriter.write(UnsafeSorterSpillWriter.java:136)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.spillIterator(UnsafeExternalSorter.java:576)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.spill(UnsafeExternalSorter.java:231)
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:227)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:190)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:317)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:117)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:433)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.allocateMemoryForRecordIfNecessary(UnsafeExternalSorter.java:452)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.insertRecord(UnsafeExternalSorter.java:487)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.insertRow(UnsafeExternalRowSorter.java:138)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.sort_addToSorter_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1(SortAggregateExec.scala:62)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1$adapted(SortAggregateExec.scala:59)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:877)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:877)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
23/10/06 12:31:57 ERROR Executor: Exception in task 0.0 in stage 10.0 (TID 42)
org.apache.spark.memory.SparkOutOfMemoryError: error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@140454d8 : No space left on device
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:253)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:190)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:317)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:117)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:433)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.allocateMemoryForRecordIfNecessary(UnsafeExternalSorter.java:452)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.insertRecord(UnsafeExternalSorter.java:487)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.insertRow(UnsafeExternalRowSorter.java:138)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.sort_addToSorter_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1(SortAggregateExec.scala:62)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1$adapted(SortAggregateExec.scala:59)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:877)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:877)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
23/10/06 12:31:57 ERROR Executor: Exception in task 3.0 in stage 10.0 (TID 45)
org.apache.spark.memory.SparkOutOfMemoryError: error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@6ecfbc2d : No space left on device
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:253)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:190)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:317)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:117)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:433)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.allocateMemoryForRecordIfNecessary(UnsafeExternalSorter.java:452)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.insertRecord(UnsafeExternalSorter.java:487)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.insertRow(UnsafeExternalRowSorter.java:138)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.sort_addToSorter_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1(SortAggregateExec.scala:62)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1$adapted(SortAggregateExec.scala:59)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:877)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:877)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
23/10/06 12:31:57 WARN TaskSetManager: Lost task 0.0 in stage 10.0 (TID 42) (192.168.1.12 executor driver): org.apache.spark.memory.SparkOutOfMemoryError: error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@140454d8 : No space left on device
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:253)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:190)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:317)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:117)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:433)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.allocateMemoryForRecordIfNecessary(UnsafeExternalSorter.java:452)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.insertRecord(UnsafeExternalSorter.java:487)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.insertRow(UnsafeExternalRowSorter.java:138)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.sort_addToSorter_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1(SortAggregateExec.scala:62)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1$adapted(SortAggregateExec.scala:59)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:877)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:877)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

23/10/06 12:31:57 ERROR TaskSetManager: Task 0 in stage 10.0 failed 1 times; aborting job
23/10/06 12:31:57 WARN TaskSetManager: Lost task 3.0 in stage 10.0 (TID 45) (192.168.1.12 executor driver): org.apache.spark.memory.SparkOutOfMemoryError: error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@6ecfbc2d : No space left on device
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:253)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:190)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:317)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:117)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:433)

Py4JJavaError: An error occurred while calling o45.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 10.0 failed 1 times, most recent failure: Lost task 0.0 in stage 10.0 (TID 42) (192.168.1.12 executor driver): org.apache.spark.memory.SparkOutOfMemoryError: error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@140454d8 : No space left on device
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:253)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:190)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:317)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:117)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:433)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.allocateMemoryForRecordIfNecessary(UnsafeExternalSorter.java:452)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.insertRecord(UnsafeExternalSorter.java:487)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.insertRow(UnsafeExternalRowSorter.java:138)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.sort_addToSorter_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1(SortAggregateExec.scala:62)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1$adapted(SortAggregateExec.scala:59)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:877)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:877)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2844)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2780)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2779)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2779)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1242)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1242)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1242)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3048)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2982)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2971)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
Caused by: org.apache.spark.memory.SparkOutOfMemoryError: error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@140454d8 : No space left on device
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:253)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:190)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:317)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:117)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:433)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.allocateMemoryForRecordIfNecessary(UnsafeExternalSorter.java:452)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.insertRecord(UnsafeExternalSorter.java:487)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.insertRow(UnsafeExternalRowSorter.java:138)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.sort_addToSorter_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1(SortAggregateExec.scala:62)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1$adapted(SortAggregateExec.scala:59)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:877)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:877)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

23/10/06 12:32:05 WARN TaskSetManager: Lost task 4.0 in stage 10.0 (TID 46) (192.168.1.12 executor driver): TaskKilled (Stage cancelled: Job aborted due to stage failure: Task 0 in stage 10.0 failed 1 times, most recent failure: Lost task 0.0 in stage 10.0 (TID 42) (192.168.1.12 executor driver): org.apache.spark.memory.SparkOutOfMemoryError: error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@140454d8 : No space left on device
	at org.apache.spark.memory.TaskMemoryManager.trySpillAndAcquire(TaskMemoryManager.java:253)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:190)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:317)
	at org.apache.spark.memory.MemoryConsumer.allocatePage(MemoryConsumer.java:117)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.acquireNewPageIfNecessary(UnsafeExternalSorter.java:433)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.allocateMemoryForRecordIfNecessary(UnsafeExternalSorter.java:452)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter.insertRecord(UnsafeExternalSorter.java:487)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.insertRow(UnsafeExternalRowSorter.java:138)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.sort_addToSorter_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage5.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1(SortAggregateExec.scala:62)
	at org.apache.spark.sql.execution.aggregate.SortAggregateExec.$anonfun$doExecute$1$adapted(SortAggregateExec.scala:59)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:877)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:877)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:364)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:328)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:104)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Driver stacktrace:)

In [22]:
result_df.filter(result_df.flight_through_area == 0).show()

+--------------------+----+-------------------+
|            flightid|data|flight_through_area|
+--------------------+----+-------------------+
|b582cf27433b5d6d9...|NULL|                  0|
|6412d5488debf415d...|NULL|                  0|
|d497715a693c91da1...|NULL|                  0|
|75d7364b40314c8dc...|NULL|                  0|
|604e406d20bf888bb...|NULL|                  0|
|8460e37f0e3755c1d...|NULL|                  0|
|d8dd7108ccbd3c6d5...|NULL|                  0|
|8f95b379e3682f4e1...|NULL|                  0|
|1b68738d5db3e1cd6...|NULL|                  0|
|494580e6170518d72...|NULL|                  0|
|0559c7a9e03ed1be3...|NULL|                  0|
|b8a114b07588d98c6...|NULL|                  0|
|3cca1ca248343401f...|NULL|                  0|
|12b4754683411a8da...|NULL|                  0|
|d9ce275aa4ad50068...|NULL|                  0|
|e2e6c4853c0f87d92...|NULL|                  0|
|75f6dac82caaa87bb...|NULL|                  0|
|38fba00a4d55bbfde...|NULL|                  0|
|1c7e1a11b19ab1af1...|NULL|                  0|
|7b7236023a33923ef...|NULL|                  0|
+--------------------+----+-------------------+
only showing top 20 rows